### PR TITLE
Added library name to example filenames

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by brentru — CHANGES_REQUESTED** [review]
Please add the new filenames to https://github.com/adafruit/Adafruit_CircuitPython_SimpleIO/blob/master/docs/examples.rst

**Comment by evaherrada** [comment]
This is the error Travis is giving me:
```
E: 53,13: Module 'pulseio' has no 'PWMOut' member (no-member)
The command "pylint simpleio.py" exited with 2.
```
I've verified that PWMOut exists, in the pulseio library so I'm not sure what the issue is. I can put in an issue, but I'll have to check using simpleio on a circuitpython board first

**Comment by brentru** [comment]
I manually rebuilt `master` on Travis and it looks like this library hits a similar issue there:
https://travis-ci.com/adafruit/Adafruit_CircuitPython_SimpleIO/jobs/198065217#L571

**Comment by sommersoft** [comment]
I looked into at the pylint error earlier, on the other PR (we need to pick one; they're for the same issue). 

Not sure why its popping up now, and not before.

I think the simple answer is to disable pylint for the offending code, which is done in other libraries.
Line 53 in `simpleio.py`:
```py
try:
    # pin with PWM
    #pylint: disable=no-member
    with pulseio.PWMOut(pin, frequency=int(frequency), variable_frequency=False) as pwm:
        pwm.duty_cycle = 0x8000
        time.sleep(duration)
    #pylint: enable=no-member
```

**Review by makermelissa — APPROVED** [review]
Looks like it's passing fine now. Thanks

**Comment by makermelissa** [comment]
Thanks @dherrada

**Pull request merged**
