### PR TITLE
Add temperature conversion helper to SimpleIO

### PR DESCRIPTION
**Pull request by CedarGroveStudios**
_convert_temp(temp_f=None, temp_c=None)_ is an often used Celsius-to-Fahrenheit / Fahrenheit-to-Celsius conversion helper that would like to find a nice home, perhaps in  _SimpleIO_. When a value _temp_f_ is supplied, a value in Celsius is returned; _temp_c_ returns a value in Fahrenheit. _None_ is returned for other input conditions.

The UI syntax is: 
```python
from simpleio import convert_temp

# Convert from Fahrenheit to Celsius
sensor_1_f = 212  # sensor temperature in degrees Fahrenheit
sensor_1_c = convert_temp(temp_f=sensor_1_f)
print("Sensor: %6.2f Fahrenheit = %6.2f Celsius" % (sensor_1_f, sensor_1_c))

# Convert from Celsius to Fahrenheit
sensor_2_c = 100  # sensor temperature in degrees Celsius
sensor_2_f = convert_temp(temp_c=sensor_2_c)
print("Sensor: %6.2f Celsius = %6.2f Fahrenheit" % (sensor_2_c, sensor_2_f))
```

### CODE REVIEW

**Comment by tannewt** [comment]
I'm not sure I like using the kwargs to encode the units. What do you think about separate functions?

It is probably worth creating a separate unit conversion library because its purpose would be clearer than SimpleIO. (SimpleIO really is the Arduino compatible function library.) It could have a `temperature` module with `convert_celsius_to_fahrenheit()` and `convert_fahrenheit_to_celsius()`.

**Comment by brentru** [comment]
I like the idea of a `CircuitPython_Unit_Conversion` library. Might be useful for more complicated unit conversions and formulas like AQI, too.

**Comment by ladyada** [comment]
@brentru you mean like.... SENSORLAB!@?!

**Comment by CedarGroveStudios** [comment]
I like the unit conversion library approach. I'll close this PR and throw together some ideas. Would be surprised if something similar hadn't been done before.

**Comment by tannewt** [comment]
I think Python's best API for this is Pint but it is pretty heavyweight: https://pint.readthedocs.io/en/latest/

**Comment by CedarGroveStudios** [comment]
Like that it contains a cornucopia of conversions, but may be too comprehensive and cryptic for a typical CircuitPython user. However, the technique of defining the temperature scale as an attribute of the value might be useful.  

sensor = convert_temp()

sensor.deg_celsius = 100
print("Fahrenheit:", sensor.deg_fahrenheit)

**Comment by CedarGroveStudios** [comment]
sensor = convert_temp()

**Comment by brentru** [comment]
I like the conversion as an attribute of the sensor like:

`sensor.deg_c`
`sensor.deg_f`

**Comment by CedarGroveStudios** [comment]
Opens the possibility for a library of converters, as well.

from converters import convert_temp, convert_length, convert_ohms_law

**Comment by CedarGroveStudios** [comment]
Here's an example of the latest temperature converter class using the suggested `units` attribute.
https://github.com/CedarGroveStudios/Converters/

```
>>> from cedargrove_converters.thermo import ConvertTemperature()
>>> sensor = ConvertTemperature()
>>> sensor.deg_f = 212
>>> sensor.deg_c
100.0
>>> sensor.k
373.15
>>> sensor.deg_c = 0
>>> sensor.k
273.15
>>> sensor.deg_f
32.0
>>> 
```
If this is an acceptable schema, I plan to proceed with a library of converters including angle, music(notes, freq), ohms_law, speed(velocity), time -- as my projects demand and as time allows.

**Comment by brentru** [comment]
I don't like calling your converter, `sensor`. That should be reserved for the sensor itself. what about...

```
i2c_bus = busio.I2C(board.SCL, board.SDA)
adt = adafruit_adt7410.ADT7410(i2c_bus, address=0x48)

# initialize a new temperature conversion object
converter = Temperature()
converter.deg_c = adt.temperature
```

> If this is an acceptable schema, I plan to proceed with a library of converters including angle, music(notes, freq), ohms_law, speed(velocity), time

I like all of these converters and will gladly add to them.

Sidebar - The primary issue I have with this approach is the converter requires the user to have knowledge of what type of data their sensor produces, instead of the code knowing the `adt7410` sensor only reads the temperature in degrees celsius. This is an idea I'd like to implement in a future version of SensorLab (see: https://github.com/adafruit/Adafruit_SensorLab/blob/master/Adafruit_SensorLab.cpp#L216).

**Comment by caternuson** [comment]
I like the first suggestion by @tannewt above. Fancier things can be done, but I think just a simple collection of converter functions would be the most beginner friendly. The default sensor units are hopefully well understood by the library docs as well as the design docs:
https://circuitpython.readthedocs.io/en/4.x/docs/design_guide.html#sensor-properties-and-units
The library layout could also follow that - module names would match property name. Then inside each would just be a bunch of `unitA_to_unitB()` functions.
```python
from unit_converter.temperature import celsius_to_fahrenheit
temperature = celsius_to_fahrenheit(sensor.temperature)
```
Can even have conversion work on tuples:
```python
from unit_converter.acceleration import mps_to_mph
x, y, z = mps_to_mph(sensor.acceleration)
```

**Comment by CedarGroveStudios** [comment]
The approach I'm using is not to create an instance of a converter, per say, but to create an instance of a sensor value with multiple inherent unit attributes. The sensor variable could be named workshop_hvac_return for example. Is that abstracting it too much?

**Comment by tannewt** [comment]
@CedarGroveStudios I think that is basically the way Pint works. It wraps values in objects to associate a unit with them. I wouldn't do that in CircuitPython because objects take more memory than plain numbers.

I like @caternuson's suggestion. Have one file/module for every value type so that only those of use can be imported (just like `temperature` in the example.)

**Comment by CedarGroveStudios** [comment]
@tannewt @caternuson Ah. Memory economics. I'll take another shot at it with those suggestions. If I need more attributes for a particular project's object, I can select multiple converter modules from the library. Cool.

**Comment by CedarGroveStudios** [comment]
Here's the current schema for temperature based on the comments. I'll expand and test it for Ohm's Law and a couple of time converters tonight. Thanks @tannewt, @caternuson, and @brentru for your ideas and suggestions!
### Temperature
>##### Celsius to Fahrenheit Converter
```python
>>> from unit_converter.temperature import celsius_to_fahrenheit
>>> celsius_to_fahrenheit(100)
212.0
>>> celsius_to_fahrenheit(0)
32.0
>>>
```
>##### Fahrenheit to Celsius Converter
```python
>>> from unit_converter.temperature import fahrenheit_to_celsius
>>> fahrenheit_to_celsius(32)
0.0
>>> fahrenheit_to_celsius(212)
100.0
>>>
```

repo: [https://github.com/CedarGroveStudios/Unit_Converter](url)

**Pull request closed without merging**
